import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for the auto-generated SDK API reference produced by TypeDoc.
 * `autogenerated` traverses the `sdk-api/` folder built by `npm run gen:sdk-api`.
 */
const sidebars: SidebarsConfig = {
  sdkApiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
